name: Build iOS IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          export THEOS=/opt/theos
          sudo mkdir -p $THEOS
          sudo chown -R $USER $THEOS
          git clone --recursive https://github.com/theos/theos.git $THEOS
      - name: Build
        run: |
          export THEOS=/opt/theos
          # On laisse make se débrouiller sans forcer le SDK 10.3 pour l'instant
          make
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Snake-IPA
          path: packages/*.ipa
