name: Build iOS IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          export THEOS=/opt/theos
          sudo mkdir -p $THEOS
          sudo chown -R $USER $THEOS
          git clone --recursive https://github.com/theos/theos.git $THEOS
      - name: Build
        run: |
          export THEOS=/opt/theos
          # Assure-toi que 'snake' est bien le nom du dossier où est ton Makefile
          cd snake
          make
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Snake-IPA
          path: snake/packages/*.ipa
